---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: amqp-messaging-network
    version: {{ .Chart.AppVersion }}
    group: {{ .Values.project.groupId }}
  name: hono-dispatch-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amqp-messaging-network
      role: router
      group: {{ .Values.project.groupId }}
  template:
    metadata:
      labels:
        app: amqp-messaging-network
        role: router
        version: {{ .Chart.AppVersion }}
        group: {{ .Values.project.groupId }}
    spec:
      containers:
      - command:
        - /sbin/qdrouterd
        - -c
        - /etc/hono/qdrouterd-with-broker.json
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: {{ .Values.dispatchRouter.image.name }}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "512Mi"
        livenessProbe:
          initialDelaySeconds: 180
          periodSeconds: 9
          tcpSocket:
            port: 5672
          timeoutSeconds: 1
        name: apache-qpid-dispatch-router
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          tcpSocket:
            port: 5672
          timeoutSeconds: 1
        securityContext:
          privileged: false
        volumeMounts:
        - mountPath: /etc/hono
          name: config
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: hono-dispatch-router-conf
